default: &default
  adapter: mysql2
  encoding: utf8
  database: inmax
  pool: 5
  username: root
  password: 


development:
  <<: *default


test:
  <<: *default
  database: test_inmax


production:
  <<: *default